FROM golang:alpine3.7 AS builder
RUN apk update && apk add --no-cache git
RUN git clone https://github.com/jmhobbs/terminal-parrot
WORKDIR terminal-parrot
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o /parrot parrot.go data.go draw.go

FROM scratch
COPY --from=builder /parrot /parrot
ENTRYPOINT ["/parrot"]

